package database_entities.exceptions;

import database_entities.FriendRequest;
import database_entities.FriendRequest.FriendRequestStatus;

public class FriendRequestExistsException extends RuntimeException{
	/**
	 * Auto-generated by Eclipse
	 */
	private static final long serialVersionUID = -6637713209564952521L;
	private String message = null;
	private FriendRequest.FriendRequestStatus status;
	
    public FriendRequestExistsException(FriendRequestStatus stat) {
        super();
    	this.status = stat;
    }
 
    public FriendRequestExistsException(String message, FriendRequestStatus stat) {
        super(message);
        this.message = message;
        this.status = stat;
    }
 
    public FriendRequestExistsException(Throwable cause) {
        super(cause);
    }
 
    public FriendRequestStatus getStatus() {
    	return this.status;
    }
    
    @Override
    public String toString() {
        return message;
    }
 
    @Override
    public String getMessage() {
        return message;
    }
}
