package database_entities.exceptions;

public class FriendRequestDoesNotExistException extends RuntimeException {
	
	
	/**
	 * Auto-generated by Eclipse
	 */
	private static final long serialVersionUID = -3055454409427426336L;
	private String message = null;
	
    public FriendRequestDoesNotExistException() {
        super();
    }
 
    public FriendRequestDoesNotExistException(String message) {
        super(message);
        this.message = message;
    }
 
    public FriendRequestDoesNotExistException(Throwable cause) {
        super(cause);
    }
    
    @Override
    public String toString() {
        return message;
    }
 
    @Override
    public String getMessage() {
        return message;
    }
}
