package database_entities.exceptions;

public class LoadDBWithCSVFailed extends RuntimeException{
	
	/**
	 * Auto-generated by Eclipse
	 */
	private static final long serialVersionUID = -4559598538033641539L;
	
	private String message = null;
	 
    public LoadDBWithCSVFailed() {
        super();
    }
 
    public LoadDBWithCSVFailed(String message) {
        super(message);
        this.message = message;
    }
 
    public LoadDBWithCSVFailed(Throwable cause) {
        super(cause);
    }
 
    @Override
    public String toString() {
        return message;
    }
 
    @Override
    public String getMessage() {
        return message;
    }
}
