package database_entities.exceptions;

public class RepositoryFactoryNotInitiated extends Exception{
		
	/**
	 * Auto-generated by Eclipse
	 */
	private static final long serialVersionUID = 8204646138825640148L;
	
	
	private String message = null;
	 
    public RepositoryFactoryNotInitiated() {
        super();
    }
 
    public RepositoryFactoryNotInitiated(String message) {
        super(message);
        this.message = message;
    }
 
    public RepositoryFactoryNotInitiated(Throwable cause) {
        super(cause);
    }
 
    @Override
    public String toString() {
        return message;
    }
 
    @Override
    public String getMessage() {
        return message;
    }
}
