package database_entities.exceptions;

public class UserObjectNotInitializedForOperation extends RuntimeException{
	
	/**
	 * Auto-generated by Eclipse
	 */
	private static final long serialVersionUID = 4790646610919975999L;

	private String message;
	
	public UserObjectNotInitializedForOperation() {
        super();
    }
 
    public UserObjectNotInitializedForOperation(String message) {
        super(message);
        this.message = message;
    }
 
    public UserObjectNotInitializedForOperation(Throwable cause) {
        super(cause);
    }
 
    @Override
    public String toString() {
        return message;
    }
 
    @Override
    public String getMessage() {
        return message;
    }
}
